"""Field ids included in the isolated values{} SQLi sweep."""

TEXT_FIELDS = [
    "param-administration-device", "param-api-name", "param-applicant",
    "param-applicant-confirmation", "param-atc-code", "param-atc-comments",
    "param-atc-name", "param-atc-name-kz", "param-atc-name-ru",
    "param-composition", "param-composition-table", "param-contract-number",
    "param-dispensing-comment", "param-dosage", "param-dosage-amount",
    "param-export-country", "param-export-trade-name-en",
    "param-export-trade-name-kz", "param-export-trade-name-ru",
    "param-export-trade-names", "param-foreign-registrations", "param-holder",
    "param-inn", "param-inn-comments", "param-inn-en", "param-inn-kz",
    "param-inn-ru", "param-manufacturer", "param-manufacturer-address",
    "param-manufacturer-contact", "param-manufacturer-permits",
    "param-manufacturer-role", "param-manufacturers", "param-mi-applicant-confirmation",
    "param-mi-applicant-contact", "param-mi-application-area",
    "param-mi-authorized-representative", "param-mi-basis",
    "param-mi-biological-testing", "param-mi-clinical-testing",
    "param-mi-contract-number", "param-mi-gmdn-code", "param-mi-instructions-info",
    "param-mi-intended-purpose", "param-mi-labeling-info", "param-mi-mfr-actual-address",
    "param-mi-mfr-country", "param-mi-mfr-email", "param-mi-mfr-head",
    "param-mi-mfr-legal-address", "param-mi-mfr-legal-form", "param-mi-mfr-name-en",
    "param-mi-mfr-name-kz", "param-mi-mfr-name-ru", "param-mi-mfr-permit-number",
    "param-mi-mfr-phone", "param-mi-mfr-type", "param-mi-model", "param-mi-name-en",
    "param-mi-name-kz", "param-mi-name-ru", "param-mi-nomenclature-code",
    "param-mi-payer-account", "param-mi-payer-actual-address", "param-mi-payer-bank",
    "param-mi-payer-bik", "param-mi-payer-bin", "param-mi-payer-country",
    "param-mi-payer-currency-account", "param-mi-payer-email", "param-mi-payer-fax",
    "param-mi-payer-iin", "param-mi-payer-knp", "param-mi-payer-legal-address",
    "param-mi-payer-name", "param-mi-payer-person", "param-mi-payer-phone",
    "param-mi-payment-subject", "param-mi-post-market-history", "param-mi-qms-info",
    "param-mi-registration-number", "param-mi-rep-actual-address",
    "param-mi-rep-applicant-head", "param-mi-rep-authority-number",
    "param-mi-rep-bin-iin", "param-mi-rep-country", "param-mi-rep-email",
    "param-mi-rep-legal-address", "param-mi-rep-name", "param-mi-rep-phone",
    "param-mi-risk-rule", "param-mi-shelf-life-value", "param-mi-software-version",
    "param-mi-storage-conditions", "param-mi-tech-characteristic-kz",
    "param-mi-tech-characteristic-ru", "param-mi-technical-testing",
    "param-mi-transport-conditions", "param-mi-variants",
    "param-mi-variation-details-table", "param-mi-variation-new-value",
    "param-mi-variation-old-value", "param-mi-warranty-value",
    "param-orphan-decision-number", "param-orphan-registration-number",
    "param-packaging", "param-patent-trademark", "param-payment-request",
    "param-payment-subject", "param-production-sites", "param-qc-lab-address",
    "param-qc-lab-email", "param-qc-lab-name", "param-qc-lab-phone",
    "param-reference-product", "param-registration-certificate-info",
    "param-registration-number", "param-shelf-life", "param-significant-excipients",
    "param-storage-conditions", "param-trade-name", "param-trade-name-en",
    "param-trade-name-kz", "param-trade-name-ru", "param-transfer-site",
    "param-transport-conditions", "param-use-period-after-dissolution-amount",
    "param-use-period-after-opening", "param-use-period-after-opening-amount",
    "param-variation-changes-table", "param-variation-code",
    "param-variation-details-table", "param-variation-linked-changes",
    "param-variation-new-value", "param-variation-old-value",
]

CHOICE_FIELDS = [
    "param-additional-monitoring", "param-administration-route",
    "param-administration-routes", "param-api-special-status", "param-aseptic",
    "param-atc-enabled", "param-bioequivalence-required", "param-biological-flag",
    "param-cis-manufacturer", "param-clinical-studies", "param-contains-gmo",
    "param-dispensing", "param-dosage-form", "param-dosage-unit",
    "param-dossier-type", "param-expertise-mode", "param-holder-first-ls-registration",
    "param-human-animal-origin", "param-immunobiological-flag",
    "param-lab-testing-required", "param-license-or-patent-active",
    "param-manufacturer-country", "param-mi-accelerated-expertise",
    "param-mi-contains-medicine", "param-mi-implantable", "param-mi-is-kit",
    "param-mi-ivd", "param-mi-ivd-closed-system", "param-mi-measuring",
    "param-mi-production-mode", "param-mi-registration-unlimited",
    "param-mi-rep-authority-doc", "param-mi-risk-class", "param-mi-shelf-life-unit",
    "param-mi-sterile", "param-mi-type", "param-mi-variation-area",
    "param-mi-variation-class", "param-mi-warranty-unit", "param-new-api-flag",
    "param-new-excipient", "param-nonclinical-studies", "param-object-type",
    "param-orphan-refusal-flag", "param-orphan-status", "param-orphan-status-state",
    "param-procedure", "param-product-type", "param-qc-lab-country",
    "param-ru-unlimited", "param-sterile", "param-trademark-required",
    "param-transfer-enabled", "param-use-period-after-dissolution-unit",
    "param-use-period-after-opening-unit", "param-variation-area",
    "param-variation-class", "param-who-prequalification",
]

DATE_FIELDS = [
    "param-contract-date", "param-contract-term", "param-mi-contract-date",
    "param-mi-mfr-permit-expiry-date", "param-mi-mfr-permit-issue-date",
    "param-mi-registration-expiry-date", "param-mi-registration-issue-date",
    "param-mi-rep-authority-expiry-date", "param-mi-rep-authority-issue-date",
    "param-orphan-assigned-date", "param-orphan-refusal-date",
    "param-orphan-withdrawal-date", "param-ru-expiry-date", "param-ru-issue-date",
]

ALL_FIELDS = TEXT_FIELDS + CHOICE_FIELDS + DATE_FIELDS
